### ISSUE TITLE
Examples are not working on Arduino IDE 1.6.7 Windows

### ISSUE THREAD

**Issue by vlna** [devicehubnet/devicehub_cpp_arduino#1]
DeviceHub.h:4:23: fatal error: uuid/uuid.h: No such file or directory

**Comment by kelemenandras** [comment]
I do have the same problem using Arduino 1.6.4 on mac os x:

fatal error: uuid/uuid.h: No such file or directory
